[package]
name = "valida-vm-api-test"
version = "0.1.0"
edition = "2021"

[dependencies]
tempfile = "3.15.0"

[target.'cfg(target_arch = "x86_64")'.dependencies]
valida-vm-api-linux-x86 = "0.10.0"

[target.'cfg(target_arch = "aarch64")'.dependencies]
valida-vm-api-linux-arm = "0.10.0"
